Fix typo in set numbering
dearshrewdwit/water_test pull request #2
Opened 2018-01-28 18:46 UTC by ealitten

2018-01-28 22:05 UTC, korki reviewed
Nice and clean solution. It's missing a bit of general ruby coding style, but at least you're consistent ;)

2018-01-28 22:05 UTC, korki commented on lib/water.rb
> +    raise TypeError unless towers.kind_of?(Array)
👍

2018-01-28 22:05 UTC, korki commented on lib/water.rb
> +    towers.each_with_index { |tower_height,index|
For multiline blocks use do..end
Space after coma

2018-01-28 22:28 UTC, ealitten commented
Oops, this was supposed to just fix the numbering in the spec, I forgot it would update with later commits! I realised the solution could be updated to only iterate through the array three times in total, although at the cost of some cleanliness

2018-01-30 13:11 UTC, dearshrewdwit requested changes
@ealitten good job! 

Next question: How does this solution in with your idea of OOP in ruby?

What would you change and why?

2018-01-30 13:11 UTC, dearshrewdwit commented on lib/water.rb
> +    towers.each_with_index { |tower_height,index|
@korki ❤️

2018-01-30 13:12 UTC, dearshrewdwit commented on lib/water.rb
> +    raise TypeError unless towers.kind_of?(Array)
ermm 👎

2018-01-30 13:14 UTC, dearshrewdwit commented on lib/water.rb
> +    raise TypeError unless towers.kind_of?(Array)
I forget the input type-check is actually in the spec 😱

2018-02-21 16:37 UTC, closed without merging